POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mario de la cruz",
    "number": "66666666666"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex"
}