POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex",
    "number": "12345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex"
}